# Prometheus Application Manifest
# This is the permanent, unique identifier for your application.
namespace: io.github.jneums.the-weather-oracle

# This section contains all data for a specific version.
submission:
  # --- Core App Information ---
  name: The Weather Oracle
  description: A verifiable on-chain weather oracle using IC HTTP outcalls to deliver real-world weather data for AI agents.
  publisher: Atlas Labs
  category: Data & Oracles

  # --- Technical & Marketing Details ---
  repo_url: https://github.com/jneums/the-weather-oracle
  mcp_path: /mcp
  why_this_app: AI agents need data they can trust. Off-chain APIs are a black box and a single point of failure. The Weather Oracle solves this by running 100% on the Internet Computer. Its data-fetching logic is transparent and verifiable, providing a reliable source of truth for any mission-critical, weather-dependent application.
  key_features:
    - "On-Chain & Verifiable: Logic runs transparently as a smart contract, preventing tampering."
    - "Reliable Weather Data: Fetches detailed forecasts from the commercial-grade Visual Crossing API."
    - "Hourly & Daily Forecasts: Two distinct tools provide weather data for the day (hourly) or week (daily)."
    - "Built for Agents: Provides a secure, trust-minimized data source for consumers."
  tags:
    - weather
    - oracle
    - data
    - api
    - real-world-data
    - on-chain
    - verifiable
    - trust
    - ai-agent
    - developer-tools

  # --- Visuals (Replace with your actual asset URLs) ---
  visuals:
    icon_url: https://github.com/jneums/the-weather-oracle/releases/download/v1.0.1-assets/icon-the-weather-oracle.png
    banner_url: https://github.com/jneums/the-weather-oracle/releases/download/v1.0.1-assets/banner-the-weather-oracle.png
    gallery_images: [https://github.com/jneums/the-weather-oracle/releases/download/v1.0.1-assets/banner-the-weather-oracle.png]

  # --- BUILD-SPECIFIC - YOU MUST FILL THESE OUT BEFORE PUBLISHING ---
  # The full commit hash of the version you are publishing.
  # Run `git rev-parse HEAD` to get this value.
  git_commit: 461888ec0bddf71e092b4d57411f6c7091b046a6

  # The path to the compiled WASM file for this canister.
  # This is typically found in `.dfx/local/canisters/<canister_name>/<canister_name>.wasm`
  wasm_path: .dfx/local/canisters/my_mcp_server/my_mcp_server.wasm