# Prometheus Application Manifest
# This is the permanent, unique identifier for your application.
namespace: io.github.jneums.the-weather-oracle

# This section contains all data for a specific version. This entire package will be submitted for review and locked to the audit of this version.
submission:
  # --- Core App Information ---
  name: The Weather Oracle
  description: A verifiable, on-chain weather oracle powered by IC HTTP outcalls. It delivers trustworthy, real-world weather data from multiple reputable sources directly to AI agents.
  publisher: Atlas Labs
  category: Data & Oracles

  # --- Technical & Marketing Details ---
  repo_url: https://github.com/jneums/the-weather-oracle
  mcp_path: /mcp
  why_this_app: AI agents and smart contracts require data they can trust. Centralized, off-chain APIs create a security risk, as their data can be manipulated or become a single point of failure. The Weather Oracle solves this problem of trust. Its logic runs entirely on the Internet Computer, meaning its process for fetching, aggregating, and serving data is transparent and verifiable. It uses the IC's native HTTP outcalls to pull information from multiple reputable weather APIs, providing a single, reliable source of truth for mission-critical, weather-aware workflows.
  key_features:
    - "Verifiable On-Chain Logic: All data fetching and aggregation logic runs transparently as a smart contract, ensuring it cannot be tampered with."
    - "Reliable & Aggregated Data: Pulls from multiple reputable sources to ensure high availability and guard against single-source failure."
    - "Built for Autonomous Agents: Provides a secure, trust-minimized data source for AI agents performing on-chain actions."
    - "Simple MCP Tool Call: Integrate weather data into your app with a single, standardized function call."
  tags:
    - weather
    - oracle
    - data
    - api
    - real-world-data
    - on-chain
    - verifiable
    - trust
    - ai-agent
    - developer-tools
    - insurance
    - defi
    - utilities

  # --- Visuals (Replace with your actual asset URLs) ---
  visuals:
    icon_url: 'https://placehold.co/512x512/1A1A1A/FFFFFF/png?text=WO'
    banner_url: 'https://placehold.co/1200x630/1A1A1A/FFFFFF/png?text=The+Weather+Oracle'
    gallery_images: []

  # --- BUILD-SPECIFIC - YOU MUST FILL THESE OUT BEFORE PUBLISHING ---
  # The full commit hash of the version you are publishing.
  # Run `git rev-parse HEAD` to get this value.
  git_commit: 44dac65db4d589b4f81cc8cafbd96bb974637608

  # The path to the compiled WASM file for this canister.
  # This is typically found in `.dfx/local/canisters/<canister_name>/<canister_name>.wasm`
  wasm_path: .dfx/local/canisters/my_mcp_server/my_mcp_server.wasm